spring:
  application:
    name: orders-management-system

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=oms_db;encrypt=false;trustServerCertificate=true
    username: sa
    password: viamatica
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

security:
  jwt:
    secret: ${JWT_SECRET:ViamaticaSecretKeyForJWTTokenGenerationWithMinimum256BitsLength}
    expiration: ${JWT_EXPIRATION:3600000}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400000}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    liquibase: INFO
    org.springframework.security: DEBUG